### ISSUE TITLE
Network Peripheral Support

### ISSUE THREAD

**Issue by weizhou-chaojixx** [beckus/qemu_stm32#26]
Hi beckus, 
   Our project needs to use qemu to simulate a stm32 board with Ethernet or Wifi network support. Do you have any machines in your project that can support network peripheral?

   We really appreciate your help.

**Comment by beckus** [comment]
Hello, I apologize for the delay. No, I'm sorry but none of the STM32 machines in this project support Ethernet or Wifi. I am not sure if any other projects do. For example it might be worth checking https://github.com/pebble/qemu . I imagine that implementing this kind of support would require a lot of effort.
