### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by amine177** [beckus/qemu_stm32#33]
I want to know how did you learn to change qemu's source code ? If there are any guides or tutorials please point me out. :))

**Comment by beckus** [comment]
Hello @amine177, I am sorry for the very long delay. Were you able to make any progress with QEMU?

I mainly learned by looking at the QEMU source code, searching the mailing list (https://lists.nongnu.org/archive/html/qemu-devel/), and looking at the documentation (https://wiki.qemu.org/Documentation/QOMConventions). Unfortunately, it is non-trivial to learn.
