### ISSUE TITLE
warning to error conversion disable

### ISSUE THREAD

**Issue by jmfriedt** [beckus/qemu_stm32#39]
gcc-10 will now stops on Warnings and creates an error which prevents compiling this qemu  (tested on Debian/GNU Linux unstable). I would advise, until warnings are solved, to add in the README.md autoconf command line
--disable-werror
to at least allow compilation to complete. I successfully completed compilation with
./configure --enable-debug --target-list="arm-softmmu" --disable-gtk --disable-sdl --disable-werror

**Comment by beckus** [comment]
Thank you for the suggestion @jmfriedt. I have updated the README to include --disable-werror by default when configuring (commit ef4defdf5dad2218340465d87e4d161b7655108e).
