### ISSUE TITLE
libxen incompatibility

### ISSUE THREAD

**Issue by jmfriedt** [beckus/qemu_stm32#42]
On a current (Dec. 2022) Debian/GNU Linux system, if libxen-dev is installed, the ``configure`` command will automatically enable Xen support
```
xen support       yes
```
but the API seems no longer compatible with some function no longer available, making the compilation fail. Disabling explicitly Xen support
```
./configure --enable-debug --disable-xen --disable-werror --target-list="arm-softmmu"
```
solves the issue.

**Comment by beckus** [comment]
Thank you very much @jmfriedt !
I have added this to the README.
